### ISSUE TITLE
Multiple commands in a single message can cause confusing results

### ISSUE THREAD

**Issue by SleepyLili** [SleepyLili/tlapbot#5]
A message like "!drink !points" would show points and not redeem a drink, despite the fact that drink is listed first.

discovered by samgai

**Comment by Michcioperz** [comment]
i'm assuming this is because of how if clauses are ordered here https://github.com/SleepyLili/tlapbot/blob/5838f15b1ce85eba01c5bfa0682f5380b0817f2d/tlapbot/owncast_webhooks.py#L36

**Comment by Michcioperz** [comment]
i mean it would be fine if the special command clauses used startswith like the clause for redeems

**Comment by SleepyLili** [comment]
Fixed in 1.0.1.
